# Generated by Django 4.2.16 on 2025-02-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0004_reaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('user', 'content_type', 'object_id')},
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('love', 'Love'), ('fire', 'Fire'), ('sad', 'Sad')], max_length=10),
        ),
        migrations.AlterField(
            model_name='textblog',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='textblog',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='created_at',
        ),
    ]
